config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes

  root to: 'notes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  enum priority: [:low, :middle, :high]

  def priority_to_s
    I18n.t("model.note.#{self.priority.to_s}")
  end

  def priority_to_i
    Note.priorities[self.priority.to_s]
  end
  
  def priority_to_c
    return 'primary' if self.low?
    return 'warning' if self.middle?
    return 'danger' if self.high?
  end

  def self.priority_to_list
    list = {}
    Note.priorities.each do |p, v|
      list.store I18n.t("model.note.#{p}"), p
    end
    return list
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.where(user_id: current_user.id)
    @notes = @notes.where('title like ?', "%#{params[:title]}%") unless params[:title].blank?
    @notes = @notes.where('content like ?', "%#{params[:content]}%") unless params[:content].blank?
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path, notice: 'Nota Criada' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to notes_path, notice: 'Nota Atualizada' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note foi apagada.' }
    end
  end

  private
    def set_note
      @note = Note.find_by_id(params[:id].to_i)
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :content, :date, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anotacao</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true, class: 'card p-2') do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label 'Titilo' %>
    <%= form.text_field :title, id: :note_title, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label 'Conteúdo' %>
    <%= form.text_area :content, id: :note_content, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label 'Data' %>
    <%= form.date_field :date, id: :note_date, class: 'form-control', type: 'date' %>
  </div>

  <div class="field form-group">
    <%= form.label 'Prioridade' %>
    <select name="note[priority]" class='form-control' selected='<%= @note.priority %>'>
      <% Note.priority_to_list.each do |p, v| %>
        <option value="<%= v %>" <%= 'selected' if v == @note.priority %>><%= p %></option>
      <% end  %>
    </select>
  </div>

  <div class="actions">
    <%= link_to 'Voltar', notes_path, class: 'btn btn-danger' %>
    <button class='btn btn-success'>Criar Nota</button>
  </div>
<% end %>

app/views/notes/_note_card.html.erb
<div class='col-sm-4'>
  <div class='card card-primary'>
    <div class='card-header'>
      <h4><%= note.title %></h4>
      <small>Prioridade: <span class='badge bg-<%= note.priority_to_c %>'><%= note.priority_to_s %></span></small>
    </div>
    <div class='card-body m-0 p-0 pl-2 pr-2' style='overflow-y: auto; height: 120px;'>
      <p><%= simple_format note.content %></p>
    </div>
    <div class='card-footer'>
      <%= link_to 'Editar', edit_note_path(note), class: 'btn btn-primary' %>
      <%= link_to 'Apagar', note, class: 'btn btn-danger', method: :delete, data: { confirm: 'Excluir nota?' } %>
      <p class='text-right'><small><%= l note.date %></small></p>
    </div>
  </div>
</div>

app/views/notes/edit.html.erb
<div class='container'>
  <h1>Editar nota: <%= @note.title %></h1>

  <div class='row'>
    <div class='col-sm-12'>
      <%= render 'form', note: @note %>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<% unless notice.blank? %>
<div class="alert alert-warning" role="alert">
  <%= notice %>
</div>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Minhas notas</h1>

      <div class='row'>
        <div class='col-sm-12 align-self-start'>
          <%= form_with(remote: true, class: 'card', action: notes_path, method: :get) do |form| %>
            <div class='card-body'>
              <div class='row'>
                <div class='col-sm-4'>
                  <div class='form-group'>
                    <%= form.label 'Título' %>
                    <%= form.text_field :title, class: 'form-control' %>
                  </div>
                </div>
                <div class='col-sm-6'>
                  <div class='form-group'>
                    <%= form.label 'Conteúdo' %>
                    <%= form.text_field :content, class: 'form-control' %>
                  </div>
                </div>
                <div class='col-sm-2'>
                  <div class='form-group pt-2'>
                    <button class='btn btn-primary font-weight-bold mt-4'>Buscar</button>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <hr>
      <div class='row'>
        <div class='col'>
          <h2>Notas</h2>
        </div>
        <div class='col'>
          <%= link_to 'Nova nota', new_note_path, class: 'btn btn-primary font-weight-bold' %>
        </div>
      </div>
      <div class='row' id="notes-list">
        <% @notes.each do |note| %>
          <%= render 'note_card', note: note %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notes/index.js.erb
var content = '';
<% @notes.each do |note| %>
    content += '<%= j(render 'note_card', note: note) %>'
<% end %>

$('#notes-list').html(content);

app/views/notes/new.html.erb
<div class='container'>
  <h1>Nova Nota</h1>

  <div class='row'>
    <div class='col-sm-12'>
      <%= render 'form', note: @note %>
    </div>
  </div>
</div>